//! SP1 Prover Script for Email Verification
//! 
//! This script generates SP1 proofs for email verification operations.

use clap::{Parser, Subcommand};
use sp1_sdk::{ProverClient, SP1Stdin};
use zkemail_profiling::create_test_email;

/// Include the program ELF (generated by `cargo prove build`)
const ELF: &[u8] = include_bytes!("../../elf/zkmail-sp1-program");

#[derive(Parser)]
#[command(name = "sp1-zkmail")]
#[command(about = "SP1 zkEmail prover")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Execute the program without generating a proof
    Execute {
        /// Size of test email in KB
        #[arg(long, default_value_t = 10)]
        email_size: usize,
    },
    /// Generate a core proof
    Prove {
        /// Size of test email in KB
        #[arg(long, default_value_t = 10)]
        email_size: usize,
    },
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct EmailVerificationInput {
    pub email: zkemail_core::Email,
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct EmailVerificationOutput {
    pub verification_result: zkemail_core::EmailVerifierOutput,
    pub is_valid: bool,
    pub cycle_count: u64,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();
    
    match &cli.command {
        Commands::Execute { email_size } => {
            execute_program(*email_size).await?;
        }
        Commands::Prove { email_size } => {
            prove_program(*email_size).await?;
        }
    }
    
    Ok(())
}

async fn execute_program(email_size: usize) -> Result<(), Box<dyn std::error::Error>> {
    println!("Executing SP1 zkEmail program...");
    println!("Email size: {}KB", email_size);
    
    let client = ProverClient::new();
    let mut stdin = SP1Stdin::new();
    
    // Create test email
    let test_email = create_test_email(email_size);
    let input = EmailVerificationInput { email: test_email };
    
    stdin.write(&input);
    
    // Execute the program
    let (output, report) = client.execute(ELF, stdin).run()?;
    let result = output.read::<EmailVerificationOutput>();
    
    println!("Execution completed!");
    println!("Email verification result: {}", result.is_valid);
    println!("Cycle count: {}", result.cycle_count);
    println!("Total instructions: {}", report.total_instruction_count());
    println!("Total cycles: {}", report.total_cycles());
    
    Ok(())
}

async fn prove_program(email_size: usize) -> Result<(), Box<dyn std::error::Error>> {
    println!("Generating SP1 proof for zkEmail...");
    println!("Email size: {}KB", email_size);
    
    let client = ProverClient::new();
    let mut stdin = SP1Stdin::new();
    
    // Create test email
    let test_email = create_test_email(email_size);
    let input = EmailVerificationInput { email: test_email };
    
    stdin.write(&input);
    
    // Setup the proving key and verifying key
    let (pk, vk) = client.setup(ELF);
    
    // Generate the proof
    let proof = client.prove(&pk, stdin).run()?;
    
    println!("Proof generated successfully!");
    println!("Proof size: {} bytes", proof.bytes().len());
    
    // Verify the proof
    client.verify(&proof, &vk)?;
    println!("Proof verified successfully!");
    
    Ok(())
}
